import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Button } from "../components/ui";
import { ClerkProviderWrapper } from "../components/clerk-provider";
import { AuthNav } from "../components/auth-nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProviderWrapper>
          <div className="min-h-screen">
            <header className="border-b">
              <div className="container mx-auto px-4 py-3 flex items-center justify-between">
                <h1 className="text-lg font-semibold">Exec-OS</h1>
                <div className="flex items-center gap-4">
                  <Button>Primary</Button>
                  <AuthNav />
                </div>
              </div>
            </header>

            <main className="container mx-auto px-4 py-6">{children}</main>
          </div>
        </ClerkProviderWrapper>
      </body>
    </html>
  );
}
